# This file contains the configuration for grouping the agents.
# This is a dictionnary with key being the group name and value being a list of agents.

dqn_grp :
  - dqn
  - dqn
ppo_grp :
  - ppo
  - ppo
a2c_grp :
  - a2c
  - a2c