# Training configuration for inRL
seed: Null
verbose: 2
tqdm_bar : True
do_wandb: True
do_tb : True
do_cli : False
n_episodes_training: 100000




defaults:
  - agents : three_base_rl_agents
  - metric_list : main_metrics
  - env : connect_four