# Training configuration for inRL
seed: Null
verbose: 2
tqdm_bar : True
do_wandb: True
do_tb : True
do_cli : True
n_episodes_training: 100000




defaults:
  - algos/simple_algos
  - metric_list/main_metrics
  - env : connect_four