# Training configuration for inRL
seed: Null
verbose: 2
tqdm_bar : True
do_wandb: True
do_tb : True
do_cli : False
n_episodes_training: 100000


agents:
  name: "(dqn,random)"
  group_names_to_grouped_agents_names:
    dqn_and_random:
      - dqn
      - random

metric_list:
  metric:
    vs_random:
      name: vs_random
      config: 
        eval_frequency: 2000
        n_episodes_evaluation: 500
        evaluated_player_id: 0
    episode_idx:
      name: episode_idx
      config: {}




defaults:
  - env : connect_four